### ISSUE TITLE
Large Parks Too Clustered

### ISSUE THREAD

**Issue by Jason-Patrick** [ProbableTrain/MapGenerator#45]
Large parks are generated tightly/clustered together: not distributed evenly throughout the map as one would expect.
![image](https://user-images.githubusercontent.com/65310110/81861146-c8a0ad00-9535-11ea-8fe3-1840a04c9de6.png)

**Comment by ProbableTrain** [comment]
This was intentional - for smaller maps I liked spreading the park out over multiple adjacent blocks. I can see that this looks weird. for larger maps though. This is all handled here: https://github.com/ProbableTrain/MapGenerator/blob/b46dae8c9ec0e5d4ec760fc04b36b94187f5a489/src/ts/ui/main_gui.ts#L208

At the moment, blocks are chosen sequentially instead of randomly in the blocks array, and they often happen to be adjacent in the map due to how blocks are found. To change this, you'd want to randomly pick a block to mark as a park instead. Might be nice to put an option to toggle between the park selection methods in the UI.

I'd welcome a pull request on this if you'd like.

**Comment by Jason-Patrick** [comment]
I can definitely take a crack at it.
